name: Validate `awesome.toml`

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check sorting
        id: validate
        run: bash .github/workflows/check_sorting.sh
